-- Stop execution on any error to prevent partial changes
\set ON_ERROR_STOP on

CREATE ROLE :db_user WITH
  LOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  CONNECTION LIMIT -1
  PASSWORD :'db_password';

GRANT ALL ON DATABASE :db_name TO :db_user;
GRANT ALL ON ALL TABLES IN SCHEMA public TO :db_user;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO :db_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO :db_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO :db_user;
