CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    disabled BOOLEAN NOT NULL DEFAULT FALSE,
    isAdmin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS auth_tokens (
    id SERIAL PRIMARY KEY,
    user_id INTEGER UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR(255) NOT NULL,
    ttl INTERVAL NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teams (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS team_tokens (
    token VARCHAR(255) PRIMARY KEY,
    teamId SERIAL NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    userId SERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    administrator BIT NOT NULL,

    can_add_proj BIT NOT NULL,
    can_del_proj BIT NOT NULL,

    can_add_token BIT NOT NULL,
    can_del_token BIT NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS project_teams (
    id SERIAL PRIMARY KEY,
    team_id INTEGER NOT NULL REFERENCES teams(id),
    project_id INTEGER NOT NULL REFERENCES projects(id)
);

CREATE TABLE IF NOT EXISTS project_tokens (
    token VARCHAR(255) PRIMARY KEY,
    projectId SERIAL NOT NULL REFERENCES projects(id),
    userId SERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    read BIT NOT NULL,
    write BIT NOT NULL
);

CREATE TABLE IF NOT EXISTS files (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(id),
    file_path VARCHAR(255) NOT NULL,
    file_size INTEGER NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT NOW()
);
