---
name: "python-unit-tests"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Python
      uses: actions/setup-python@v6.0.0
      with:
        python-version: "3.13"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src tests/python | tee pytest-coverage.txt

    - name: Generate authentication token from GitHub App
      id: app_token
      uses: actions/create-github-app-token@v2.1.1
      with:
        app-id: ${{ secrets.TERRAHARBOR_MAINTAINER_APP_ID }}
        private-key: ${{ secrets.TERRAHARBOR_MAINTAINER_PRIVATE_KEY }}

    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
        github-token: ${{ steps.app_token.outputs.token }}
